(function(window){var document=window.document;var console=window.console;var CAGE=window.CAGE||{};var isClassListExist=false;CAGE.util=CAGE.util||{};if("classList"in document.createElement("a"))isClassListExist=true;var hasClass_common=function(DOM,className){var pattern=new RegExp("^.*"+className+".*$");if(pattern.test(DOM.className))return true;return false};var addClass_common=function(DOM,className){if(this.hasClass(DOM,className))return;if(DOM.className==""){DOM.className=className;return}DOM.className+=
" "+className};var removeClass_common=function(DOM,className){if(!this.hasClass(DOM,className))return;if(DOM.className==className){DOM.className="";return}if(this.hasClass(DOM," "+className))DOM.className=DOM.className.replace(" "+className,"");else DOM.className=DOM.className.replace(className+" ","")};var Util={object:{extend:function(dest,src){for(var property in src)dest[property]=src[property];return dest}},dom:{hasClass:function(){if(isClassListExist)return function(DOM,className){return DOM.classList.contains(className)};
else return hasClass_common}(),addClass:function(){if(isClassListExist)return function(DOM,className){return DOM.classList.add(className)};else return addClass_common}(),removeClass:function(){if(isClassListExist)return function(DOM,className){return DOM.classList.remove(className)};else return addClass_common}()},string:{trim:function(){if("trim"in String.prototype)return function(str){return String.prototype.trim.call(str)};else return function(str){return this.ltrim(this.rtrim(str))}}(),rtrim:function(str){if("trimRight"in
String.prototype)return function(str){return String.prototype.trimRight.call(str)};else return function(str){return str.replace(/\s*$/,"")}}(),ltrim:function(str){if("trimLeft"in String.prototype)return function(str){return String.prototype.trimLeft.call(str)};else return function(str){return str.replace(/^\s*/,"")}}()},template:{compiler:function(dataObj,templateString){var resultStr=Util.string.trim(templateString);for(var variableName in dataObj)if(dataObj[variableName]===0||dataObj[variableName])resultStr=
resultStr.replace("\x3c%\x3d "+variableName+" %\x3e",dataObj[variableName]);return resultStr},getCompiler:function(){return this.compiler},get:function(orgs){var Ajax=CAGE.ajax;var url=orgs.url;var template=null;Ajax.GET({"url":url,"isAsync":false,"callback":function(templateResponse){template=JSON.parse(templateResponse)["data"]["template"]}});return template}}};CAGE.util=Util;if(typeof module!=="undefined"&&module.exports)module.exports=CAGE;else window.CAGE=CAGE})(this);
(function(window){var document=window.document;var console=window.console;var CAGE=window.CAGE||{};CAGE.ajax=CAGE.ajax||{};function _createRequest(){try{var request=new XMLHttpRequest}catch(tryMS){try{request=new ActiveXObject("Msxml2.XMLHTTP")}catch(otherMS){try{request=new ActiveXObject("Microsoft.XMLHTTP")}catch(failed){request=null}}}return request}function _responseData(e,request,callback){if(request.readyState==4)if(request.status==200){var response=request.responseText;if(response.substring(response.length-
1)==="\n")response=response.substring(0,response.length-1);callback(response)}}function removeNewLine(str){if(str.substring(str.length-1)==="\n")return str.substring(0,str.length-1);return str}function _error(evt,request,failure){if(request.detail!==undefined){failure(request.detail);return}var responseText=removeNewLine(request.responseText);var responseObj=JSON.parse(request.responseText);failure(responseObj)}function _load(evt,request,success){var targetEl=evt.target;if(request.status>=200&&request.status<
300||request.status==304){var response=removeNewLine(request.responseText);var responseObj=JSON.parse(request.responseText);var apiStatus=responseObj.status;if(apiStatus>=200&&apiStatus<300||apiStatus==304)success(responseObj);else{var errorEvt=new CustomEvent("error",{"detail":responseObj});targetEl.dispatchEvent(errorEvt)}}}function _exec(config){var method=config.method,headerObj=config.headers,url=config.url,callback=config.callback,data=config.data,isAsync=config.isAsync,success=config.success,
failure=config.failure;if(url==undefined)return;if(isAsync==undefined)isAsync=true;var request=_createRequest();if(request==undefined){console.log("Unable to create request");return}request.open(method,url,isAsync);if(callback!==undefined)request.addEventListener("readystatechange",function(e){_responseData(e,request,callback)},false);if(success!==undefined)request.addEventListener("load",function(evt){_load(evt,request,success)},false);if(failure!==undefined)request.addEventListener("error",function(evt){_error(evt,
request,failure)},false);if(headerObj!==undefined)for(var header in headerObj){var content=headerObj[header];request.setRequestHeader(header,content)}request.send(data)}function GET(config){config.method="GET";_exec(config)}function POST(config){config.method="POST";config.headers={"Content-Type":"application/x-www-form-urlencoded"};_exec(config)}function PUT(config){config.method="PUT";config.headers={"Content-Type":"application/x-www-form-urlencoded"};_exec(config)}function DELETE(config){config.method=
"DELETE";_exec(config)}CAGE.ajax={GET:GET,POST:POST,PUT:PUT,DELETE:DELETE};if(typeof module!=="undefined"&&module.exports)module.exports=CAGE;else window.CAGE=CAGE})(this);
(function(window){var document=window.document;var console=window.console;var CAGE=window.CAGE||{};CAGE.ui=CAGE.ui||{};CAGE.ui.popup=CAGE.ui.popup||{};var Dom=CAGE.util.dom;var Template=CAGE.util.template;var Ajax=CAGE.ajax;function eventEmitter(eventType){this.type=eventType;this.eventHandlers=[]}eventEmitter.prototype.add=function(handler){this.eventHandlers.push(handler)};eventEmitter.prototype.remove=function(handler){var eventHandlers=this.eventHandlers;for(var i in eventHandlers)if(eventHandlers[i]===
handler)eventHandlers.splice(i,1)};eventEmitter.prototype.dispatch=function(){var eventHandlers=this.eventHandlers;var param=undefined;for(var i in eventHandlers){param=arguments[i]?arguments[i]:undefined;eventHandlers[i](param)}};function popup(config){this.el=config.element;this.template=config.template;this.transitionEffect=config.transitionEffect?config.transitionEffect:"zoom";this.afteropen=new eventEmitter("afteropen");this.afterclose=new eventEmitter("afterclose");this.status={data:false};
this._init()}popup.prototype._init=function(){var el=this.el;var afteropen=this.afteropen;var afterclose=this.afterclose;var status=this.status;var close=this.close;el.addEventListener("click",openHandler.bind(this),false);function openHandler(event){Ajax.GET({url:this.templateUrl,callback:function(response){console.log(response);this.template=this.templateLoader(response);event.preventDefault();event.stopPropagation();var originalTarget;if(event.toElement)originalTarget=event.toElement;else if(event.originalTarget)originalTarget=
event.originalTarget;if(originalTarget===el){this._counstructDOM();var popupWrapAnimation=document.querySelector(".popup-wrap.popup-animation");popupWrapAnimation.addEventListener("transitionend",afteropenCallbackRef,false)}}.bind(this)})}function afteropenCallbackRef(event){if(event.propertyName==="-webkit-transform"&&status.data===false){var popupWrapAnimation=document.querySelector(".popup-wrap.popup-animation");popupWrapAnimation.removeEventListener("webkitTransitionEnd",afteropenCallbackRef,
false);afteropen.dispatch(document.querySelector(".popup-content"));status.data=!status.data;var popupBg=document.querySelector(".popup-bg");var popupWrap=document.querySelector(".popup-wrap");var popupContainer=document.querySelector(".popup-container");var popupContent=document.querySelector(".popup-content");var escClose=function(e){if(e.keyCode==27)close()};document.addEventListener("keyup",escClose,false);popupContainer.addEventListener("click",function(event){if(event.target===popupContainer||
event.target===popupContent){var that=this;Dom.removeClass(popupBg,"popup-ready");Dom.removeClass(popupWrap,"popup-ready");popupBg.addEventListener("transitionend",function(event){if(event.propertyName==="opacity"&&status.data===true){afterclose.dispatch(document.querySelector(".popup-content"));status.data=!status.data;var popupBg=document.querySelector(".popup-bg");var popupWrap=document.querySelector(".popup-wrap");popupBg?document.body.removeChild(popupBg):undefined;popupWrap?document.body.removeChild(popupWrap):
undefined}}.bind(that),false)}},false)}}};popup.prototype.open=function(){this.el.click()};popup.prototype.close=function(){var popupContainer=document.querySelector(".popup-container");popupContainer.click()};popup.prototype._getTemplate=function(){return this.template};popup.prototype._counstructDOM=function(){var transitionEffect=this.transitionEffect;var popupBg=document.createElement("div");Dom.addClass(popupBg,"popup-bg");Dom.addClass(popupBg,"popup-animation");var popupWrap=document.createElement("div");
Dom.addClass(popupWrap,"popup-wrap");Dom.addClass(popupWrap,"popup-animation");var popupContainer=document.createElement("div");Dom.addClass(popupContainer,"popup-container");var popupContent=document.createElement("div");Dom.addClass(popupContent,"popup-content");popupContent.innerHTML=this._getTemplate();popupContainer.appendChild(popupContent);if(transitionEffect!=undefined)Dom.addClass(popupContent,transitionEffect+"-animation-dialog");popupWrap.appendChild(popupContainer);document.body.insertAdjacentHTML("afterbegin",
popupWrap.outerHTML);document.body.insertAdjacentHTML("afterbegin",popupBg.outerHTML);var closeBtn=document.querySelector(".popup-wrap button[data-role\x3d'close']");if(closeBtn)closeBtn.addEventListener("click",this.closePopup,false);var popupWrapAnimation=document.querySelector(".popup-wrap.popup-animation");var popupBgAnimation=document.querySelector(".popup-bg.popup-animation");popupWrapAnimation.offsetHeight;popupBgAnimation.offsetHeight;popupBgAnimation.style.transform="translateY(0px)";Dom.addClass(popupWrapAnimation,
"popup-ready");Dom.addClass(popupBgAnimation,"popup-ready")};function ajaxPopup(config){this.el=config.element;this.template="!";this.transitionEffect=config.transitionEffect?config.transitionEffect:"zoom";this.templateUrl=config.templateUrl;this.templateLoader=config.templateLoader?config.templateLoader:function(response){return response};this.afteropen=new eventEmitter("afteropen");this.afterclose=new eventEmitter("afterclose");this.status={data:false};this._init()}ajaxPopup.prototype=popup.prototype;
CAGE.ui.popup={popup:popup,ajaxPopup:ajaxPopup};if(typeof module!=="undefined"&&module.exports)module.exports=CAGE;else window.CAGE=CAGE})(this);